#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/init-20-php-fpm ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

### Set Defaults
DB_PORT=${DB_PORT:-3306}

### Sanity Test
if [ ! -n "$DB_HOST" ]; then
    echo '** [teampass] ERROR: No Database Host Entered! '
    exit 1
fi

if [ ! -n "$DB_NAME" ]; then
    echo '** [teampass] ERROR: No Database Pass Entered! '
    exit 1
fi

if [ ! -n "$DB_USER" ]; then
    echo '** [teampass] ERROR: No Database User Entered! '
    exit 1
fi

if [ ! -n "$DB_PASS" ]; then
    echo '** [teampass] ERROR: No Database Pass Entered!'
    exit 1
fi


### Make sure that DB is accessible
while true; do
  mysqlcmd="mysql -u$DB_USER -h$DB_HOST -p$DB_PASS -P$DB_PORT"
  out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
  echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
  if [ $? -eq 0 ]; then
      echo "** [teampass] MariaDB Server '"$DB_HOST"' is available"
      break
  fi
  echo "** [teampass] MariaDB Server '"$DB_HOST"' unavailable. Sleeping a little bit ..."
  sleep 5
done

### Check to see if Installed, or Configured..
echo "** [teampass] Checking Teampass Files"
if [ -f ${NGINX_WEBROOT}/index.php ]; then
  echo "** [teampass] Found Teampass Files. Checking if it is configured ..."
  if [ -f ${NGINX_WEBROOT}/includes/config/settings.php ] ; then
      if [ -f ${NGINX_WEBROOT}/.version ] ; then
        if [ "$TEAMPASS_VERSION" != `head -n 1 ${NGINX_WEBROOT}/.version | awk '{print $1'}` ]; then
          echo '** [teampass] Detected New Version from original installation, Please visit your Site_URL/install/upgrade.php'
          echo $TEAMPASS_VERSION 'upgraded on '`date` | cat - ${NGINX_WEBROOT}/.version > /tmp/.version && mv /tmp/.version ${NGINX_WEBROOT}/.version
        else
          rm -rf ${NGINX_WEBROOT}/install
          chown -R ${NGINX_USER}:${NGINX_GROUP} ${NGINX_WEBROOT}
        fi
      fi  
  else
        echo "** [teampass] Teampass is not configured! Please visit the website to complete installation"
  fi
else
  echo "** [teampass] No Installation Found - Fetching Teampass Version ${TEAMPASS_VERSION}"
  mkdir -p ${NGINX_WEBROOT}
  curl https://codeload.github.com/nilsteampassnet/TeamPass/tar.gz/${TEAMPASS_VERSION}| tar xvfz - --strip 1 -C ${NGINX_WEBROOT}
  mkdir -p /www/sk
  sed -i -e 's/ \"function\*mysqli_fetch_all\",//g' ${NGINX_WEBROOT}/install/install.js
  echo '** [teampass] Please visit your Site_URL to complete installation'
  echo $TEAMPASS_VERSION 'first installed on '`date`> ${NGINX_WEBROOT}/.version
fi

### Custom File Support
if [ -d /assets/custom ] ; then
    echo "** [teampass] Custom Files Found, Copying over top of Master"
    cp -R /assets/custom/* ${NGINX_WEBROOT}
fi

chown -Rf ${NGINX_USER}:${NGINX_GROUP} ${NGINX_WEBROOT}
chown -Rf ${NGINX_USER}:${NGINX_GROUP} /www/sk

echo "** [teampass] Container Initialized - Now starting Web Services"

mkdir -p /tmp/state
touch /tmp/state/init-30-teampass
