#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="teampass"
check_service_initialized init 20-php-fpm

### Set Defaults
DB_PORT=${DB_PORT:-3306}

### Sanity Test
sanity_db

### Make sure that DB is accessible
db_ready mariadb

### Check to see if Installed, or Configured..
if [ -f ${NGINX_WEBROOT}/index.php ]; then
  print_notice "Found Teampass Files. Checking if it is configured ..."
  if [ -f ${NGINX_WEBROOT}/includes/config/settings.php ] ; then
      if [ -f ${NGINX_WEBROOT}/.version ] ; then
        if [ "$TEAMPASS_VERSION" != `head -n 1 ${NGINX_WEBROOT}/.version | awk '{print $1'}` ]; then
          print_warn "Detected New Version from original installation, Please visit your Site_URL/install/upgrade.php"
          echo $TEAMPASS_VERSION 'upgraded on '`date` | cat - ${NGINX_WEBROOT}/.version > /tmp/.version && mv /tmp/.version ${NGINX_WEBROOT}/.version
        else
          rm -rf ${NGINX_WEBROOT}/install
          chown -R ${NGINX_USER}:${NGINX_GROUP} ${NGINX_WEBROOT}
        fi
      fi  
  else
        print_warn "Teampass is not configured! Please visit the website to complete installation"
  fi
else
  print_warn "No Installation Found - Fetching Teampass Version ${TEAMPASS_VERSION}"
  mkdir -p ${NGINX_WEBROOT}
  curl https://codeload.github.com/nilsteampassnet/TeamPass/tar.gz/${TEAMPASS_VERSION}| tar xvfz - --strip 1 -C ${NGINX_WEBROOT}
  mkdir -p /www/sk
  sed -i -e 's/ \"function\*mysqli_fetch_all\",//g' ${NGINX_WEBROOT}/install/install.js
  print_warn "Please visit your Site_URL to complete installation"
  echo $TEAMPASS_VERSION 'first installed on '`date`> ${NGINX_WEBROOT}/.version
fi

### Custom File Support
if [ -d /assets/custom ] ; then
    print_warn "Custom Files Found, Copying over top of Master"
    cp -R /assets/custom/* ${NGINX_WEBROOT}
fi

chown -Rf ${NGINX_USER}:${NGINX_GROUP} ${NGINX_WEBROOT}
chown -Rf ${NGINX_USER}:${NGINX_GROUP} /www/sk

print_info "Container Initialized - Now starting Web Services"
liftoff
