version: '3.7'
services:

  teampass-app:
    image: tiredofit/teampass
    container_name: teampass-app
    links:
      - teampass-db
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:teampass.example.org
      - traefik.port=80
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=teampass-app
    volumes:
      - ./data/:/www/
      - ./logs/:/www/logs
    environment:
      - DB_HOST=teampass-db
      - DB_NAME=teampass
      - DB_USER=teampass
      - DB_PASS=userpassword
    networks:
      - proxy
      - services
    restart: always

  teampass-db:
    image: tiredofit/mariadb
    container_name: teampass-db
    volumes:
      - ./db:/var/local/db/teampass
    environment:
      - ROOT_PASS=password
      - DB_NAME=teampass
      - DB_USER=teampass
      - DB_PASS=userpassword
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
